export const ADJUST_BREAK_LENGTH = 'ADJUST_BREAK_LENGTH';
export const ADJUST_SESSION_LENGTH = 'ADJUST_SESSION_LENGTH';
export const PRESS_START = 'PRESS_START';
export const PRESS_RESET = 'PRESS_RESET';
export const PRESS_STOP = 'PRESS_STOP';
