export const ADJUST_BREAK_LENGTH = 'ADJUST_BREAK_LENGTH';
export const ADJUST_SESSION_LENGTH = 'ADJUST_SESSION_LENGTH';
export const SWITCH_STATE = 'SWITCH_STATE';
export const PRESS_RESET = 'PRESS_RESET';
export const SET_INTERVAL_ID = 'SET_INTERVAL_ID';

export const SWITCH_TYPE = 'SWITCH_TYPE';
export const TICK_TIME = 'TICK_TIME';
